### ISSUE TITLE
Too many plots?

### ISSUE THREAD

**Issue by AndreasPapageorgiou** [subisarkar/JexoSim#3]
I run the following:

`python run_jexosim.py jexosim_input_params_ex1.txt`

It produced around 40 plots in parallel on my desktop and was a bit unpleasant :-)
Not sure if this is the intended functionality or due to the fact I ran the code from the linux console, which handles plots somewhat different from Spyder.

**Comment by subisarkar** [comment]
Change sim_diagnostics  to 0 in the input configuration file to hide most of these figures.
