### ISSUE TITLE
Problem with quantum yield calculation for NIRSpec subarrays 

### ISSUE THREAD

**Issue by tagordon** [subisarkar/JexoSim#4]
For an out-of-transit simulation with the NIRSpec prism, I get the following traceback whenever I specify a subarray other than SUB2048: 

> Traceback (most recent call last):
>   File "run_jexosim.py", line 10, in <module>
>     go()
>   File "run_jexosim.py", line 7, in go
>     run_jexosim.run(input_file)
>   File "/Users/tgordon/research/nirspec/JexoSim/jexosim/run_files/run_jexosim.py", line 139, in run
>     recipe  = recipe_1(opt)
>   File "/Users/tgordon/research/nirspec/JexoSim/jexosim/run_files/recipe_1.py", line 99, in __init__
>     opt = self.run_JexoSimB(opt)
>   File "/Users/tgordon/research/nirspec/JexoSim/jexosim/run_files/recipe_1.py", line 208, in run_JexoSimB
>     noise.run(opt)
>   File "/Users/tgordon/research/nirspec/JexoSim/jexosim/modules/noise.py", line 929, in run
>     opt.data , opt.pointing_timeline = noise_simulator(opt)
>   File "/Users/tgordon/research/nirspec/JexoSim/jexosim/modules/noise.py", line 602, in noise_simulator
>     opt = fast_method(opt)
>   File "/Users/tgordon/research/nirspec/JexoSim/jexosim/modules/noise.py", line 462, in fast_method
>     zodi_photon_noise, zodi_fano_noise = calc_poisson(qy_zodi, zodi_signal)
>   File "/Users/tgordon/research/nirspec/JexoSim/jexosim/modules/noise.py", line 24, in calc_poisson
>     photon_noise = photon_noise*quantum_yield
>   File "/Users/tgordon/anaconda/envs/jexosim/lib/python3.8/site-packages/astropy-4.0.1-py3.8-macosx-10.9-x86_64.egg/astropy/units/quantity.py", line 959, in __rmul__
>     return self.__mul__(other)
>   File "/Users/tgordon/anaconda/envs/jexosim/lib/python3.8/site-packages/astropy-4.0.1-py3.8-macosx-10.9-x86_64.egg/astropy/units/quantity.py", line 943, in __mul__
>     return super().__mul__(other)
>   File "/Users/tgordon/anaconda/envs/jexosim/lib/python3.8/site-packages/astropy-4.0.1-py3.8-macosx-10.9-x86_64.egg/astropy/units/quantity.py", line 477, in __array_ufunc__
>     result = super().__array_ufunc__(function, method, *arrays, **kwargs)
> ValueError: operands could not be broadcast together with shapes (1,2048,1) (10,512,2000)

**Comment by subisarkar** [comment]
Hopefully now fixed with the new updates.  Let me know if still a problem.
